version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: elearning_postgres
    environment:
      POSTGRES_DB: elearning_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - elearning_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: elearning_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@elearning.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - elearning_network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  elearning_network:
    driver: bridge